[phases.setup]
nixPkgs = ["flutter", "sudo"]
cmds = ["adduser -D myuser", "chown -R myuser:myuser /app"]

[phases.build]
cmds = ["sudo -u myuser flutter pub get", "sudo -u myuser flutter build web --web-renderer html"]
