name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
    
    - name: Create local.properties
      run: |
        echo "sdk.dir=$ANDROID_HOME" > android/local.properties
        echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties
    
    - name: Update Flutter SDK path in settings.gradle
      run: |
        sed -i "s|flutterSdkPath = .*|flutterSdkPath = '$FLUTTER_ROOT'|g" android/settings.gradle
    
    - name: Set up Gradle Wrapper
      run: |
        cd android
        gradle wrapper
        ./gradlew wrapper --gradle-version 8.10.1
        cd ..
    
    - name: Make gradlew executable
      run: chmod +x android/gradlew
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=../app/my-release-key.jks" >> android/key.properties
    
    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks
    
    - name: Create .env file
      run: |
        echo "YOUR_ENV_VARIABLE=value" > .env
    
    - name: Build APK
      run: flutter build apk --release --verbose
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk