name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'  # Use the latest stable version
        channel: 'stable'
    
    - name: Update Kotlin version
      run: |
        sed -i 's/ext.kotlin_version = ".*"/ext.kotlin_version = "1.8.22"/' android/build.gradle
        sed -i 's/classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"/classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.22"/' android/build.gradle
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=../app/my-release-key.jks" >> android/key.properties
    
    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks
    
    - name: Create .env file
      run: |
        echo "YOUR_ENV_VARIABLE=value" > .env
    
    - name: Build APK
      run: flutter build apk --release --verbose
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk